#!/usr/bin/env sh
# httpmirror-cli - a CLI posix shell script to replace softwares' registry mirror

: << LICENSE_EOF
@include ../LICENSE
LICENSE_EOF

set -e

script_version="@var(cat version)"
build_time="@var(date -u +'%Y-%m-%d %H:%M:%S UTC')"
gen_tag="Generated by hustmirror-cli"
domains="@var(cat domains)"
domain="hustmirror.cn"
http="https"

@include utils.sh

# Not only to replace distributions but also softwares like pypi,
# npm registry, dockerhub, etc.
supported_softwares="@var(ls -1 src/mirrors/* | sed -E 's/^.+\/(.+)\.[^.]*$/\1/')"

@mirrors

@include core.sh
@include cli.sh
@include interact.sh
@include bootstrap.sh

# vim: set filetype=sh ts=4 sw=4 noexpandtab:
