name: Makefile CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Install make
      run: sudo apt install make

    - name: Build
      run: make

    - name: Run test
      run: make test
